//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RS_3
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T вид разрешения.
    /// </summary>
    //  *** Start programmer edit section *** (tВидРазрешения CustomAttributes)

    //  *** End programmer edit section *** (tВидРазрешения CustomAttributes)
    public enum tВидРазрешения
    {
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (tВидРазрешения.Строительство CustomAttributes)

        //  *** End programmer edit section *** (tВидРазрешения.Строительство CustomAttributes)
        Строительство,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (tВидРазрешения.Реконструкция CustomAttributes)

        //  *** End programmer edit section *** (tВидРазрешения.Реконструкция CustomAttributes)
        Реконструкция,
    }
}
