//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RS_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Застройщик.
    /// </summary>
    //  *** Start programmer edit section *** (ЗастройщОрг CustomAttributes)

    //  *** End programmer edit section *** (ЗастройщОрг CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗастройщикE", new string[0])]
    [View("ЗастройщОргE", new string[] {
            "Описание as \'Описание\'",
            "ОрганизЗастр as \'Организ застр\'",
            "ОрганизЗастр.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ОрганизЗастр.Наименование"})]
    [MasterViewDefineAttribute("ЗастройщОргE", "ОрганизЗастр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ЗастройщОрг : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписание;
        
        private IIS.RS_3.Организация fОрганизЗастр;
        
        private IIS.RS_3.РазрешНаСтроит fРазрешение;
        
        //  *** Start programmer edit section *** (ЗастройщОрг CustomMembers)

        //  *** End programmer edit section *** (ЗастройщОрг CustomMembers)

        
        /// <summary>
        /// Описание.
        /// </summary>
        //  *** Start programmer edit section *** (ЗастройщОрг.Описание CustomAttributes)

        //  *** End programmer edit section *** (ЗастройщОрг.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.Описание Get start)

                //  *** End programmer edit section *** (ЗастройщОрг.Описание Get start)
                string result = this.fОписание;
                //  *** Start programmer edit section *** (ЗастройщОрг.Описание Get end)

                //  *** End programmer edit section *** (ЗастройщОрг.Описание Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.Описание Set start)

                //  *** End programmer edit section *** (ЗастройщОрг.Описание Set start)
                this.fОписание = value;
                //  *** Start programmer edit section *** (ЗастройщОрг.Описание Set end)

                //  *** End programmer edit section *** (ЗастройщОрг.Описание Set end)
            }
        }
        
        /// <summary>
        /// Застройщик.
        /// </summary>
        //  *** Start programmer edit section *** (ЗастройщОрг.ОрганизЗастр CustomAttributes)

        //  *** End programmer edit section *** (ЗастройщОрг.ОрганизЗастр CustomAttributes)
        [NotNull()]
        public virtual IIS.RS_3.Организация ОрганизЗастр
        {
            get
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.ОрганизЗастр Get start)

                //  *** End programmer edit section *** (ЗастройщОрг.ОрганизЗастр Get start)
                IIS.RS_3.Организация result = this.fОрганизЗастр;
                //  *** Start programmer edit section *** (ЗастройщОрг.ОрганизЗастр Get end)

                //  *** End programmer edit section *** (ЗастройщОрг.ОрганизЗастр Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.ОрганизЗастр Set start)

                //  *** End programmer edit section *** (ЗастройщОрг.ОрганизЗастр Set start)
                this.fОрганизЗастр = value;
                //  *** Start programmer edit section *** (ЗастройщОрг.ОрганизЗастр Set end)

                //  *** End programmer edit section *** (ЗастройщОрг.ОрганизЗастр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.RS_3.РазрешНаСтроит.
        /// </summary>
        //  *** Start programmer edit section *** (ЗастройщОрг.Разрешение CustomAttributes)

        //  *** End programmer edit section *** (ЗастройщОрг.Разрешение CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.RS_3.РазрешНаСтроит Разрешение
        {
            get
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.Разрешение Get start)

                //  *** End programmer edit section *** (ЗастройщОрг.Разрешение Get start)
                IIS.RS_3.РазрешНаСтроит result = this.fРазрешение;
                //  *** Start programmer edit section *** (ЗастройщОрг.Разрешение Get end)

                //  *** End programmer edit section *** (ЗастройщОрг.Разрешение Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ЗастройщОрг.Разрешение Set start)

                //  *** End programmer edit section *** (ЗастройщОрг.Разрешение Set start)
                this.fРазрешение = value;
                //  *** Start programmer edit section *** (ЗастройщОрг.Разрешение Set end)

                //  *** End programmer edit section *** (ЗастройщОрг.Разрешение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗастройщикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗастройщикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗастройщикE", typeof(IIS.RS_3.ЗастройщОрг));
                }
            }
            
            /// <summary>
            /// "ЗастройщОргE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗастройщОргE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗастройщОргE", typeof(IIS.RS_3.ЗастройщОрг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗастройщОрг.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfЗастройщОрг CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfЗастройщОрг CustomAttributes)
    public class DetailArrayOfЗастройщОрг : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.RS_3.DetailArrayOfЗастройщОрг members)

        //  *** End programmer edit section *** (IIS.RS_3.DetailArrayOfЗастройщОрг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗастройщОрг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗастройщОрг.
        /// </summary>
        public DetailArrayOfЗастройщОрг(IIS.RS_3.РазрешНаСтроит fРазрешНаСтроит) : 
                base(typeof(ЗастройщОрг), ((ICSSoft.STORMNET.DataObject)(fРазрешНаСтроит)))
        {
        }
        
        public IIS.RS_3.ЗастройщОрг this[int index]
        {
            get
            {
                return ((IIS.RS_3.ЗастройщОрг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.RS_3.ЗастройщОрг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
