//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RS_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Разреш на строит.
    /// </summary>
    //  *** Start programmer edit section *** (РазрешНаСтроит CustomAttributes)

    //  *** End programmer edit section *** (РазрешНаСтроит CustomAttributes)
    [AutoAltered()]
    [Caption("Разреш на строит")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РазрешНаСтроитE", new string[] {
            "Наименование as \'Наименование\'",
            "ВидРазрешения as \'Вид разрешения\'",
            "Архив as \'Архив\'",
            "ДатаРазрешения as \'Дата разрешения\'",
            "НомерРазрешения as \'Номер разрешения\'"})]
    [AssociatedDetailViewAttribute("РазрешНаСтроитE", "ОбъектСтроит", "ОбъектСтроитE", true, "", "Объект строит", true, new string[] {
            ""})]
    [View("РазрешНаСтроитL", new string[] {
            "Наименование as \'Наименование\'",
            "ВидРазрешения as \'Вид разрешения\'",
            "Архив as \'Архив\'",
            "ДатаРазрешения as \'Дата разрешения\'",
            "НомерРазрешения as \'Номер разрешения\'"})]
    public class РазрешНаСтроит : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.RS_3.tВидРазрешения fВидРазрешения;
        
        private bool fАрхив;
        
        private System.DateTime fДатаРазрешения;
        
        private int fНомерРазрешения;
        
        private IIS.RS_3.DetailArrayOfОбъектСтроит fОбъектСтроит;
        
        private IIS.RS_3.DetailArrayOfЗастройщОрг fЗастройщОрг;
        
        //  *** Start programmer edit section *** (РазрешНаСтроит CustomMembers)

        //  *** End programmer edit section *** (РазрешНаСтроит CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.Наименование CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.Наименование Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (РазрешНаСтроит.Наименование Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.Наименование Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.Наименование Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ВидРазрешения.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.ВидРазрешения CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.ВидРазрешения CustomAttributes)
        public virtual IIS.RS_3.tВидРазрешения ВидРазрешения
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ВидРазрешения Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ВидРазрешения Get start)
                IIS.RS_3.tВидРазрешения result = this.fВидРазрешения;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ВидРазрешения Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ВидРазрешения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ВидРазрешения Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ВидРазрешения Set start)
                this.fВидРазрешения = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ВидРазрешения Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ВидРазрешения Set end)
            }
        }
        
        /// <summary>
        /// Архив.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.Архив CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.Архив CustomAttributes)
        public virtual bool Архив
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.Архив Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.Архив Get start)
                bool result = this.fАрхив;
                //  *** Start programmer edit section *** (РазрешНаСтроит.Архив Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.Архив Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.Архив Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.Архив Set start)
                this.fАрхив = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.Архив Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.Архив Set end)
            }
        }
        
        /// <summary>
        /// ДатаРазрешения.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.ДатаРазрешения CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.ДатаРазрешения CustomAttributes)
        public virtual System.DateTime ДатаРазрешения
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Get start)
                System.DateTime result = this.fДатаРазрешения;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Set start)
                this.fДатаРазрешения = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ДатаРазрешения Set end)
            }
        }
        
        /// <summary>
        /// НомерРазрешения.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.НомерРазрешения CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.НомерРазрешения CustomAttributes)
        public virtual int НомерРазрешения
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.НомерРазрешения Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.НомерРазрешения Get start)
                int result = this.fНомерРазрешения;
                //  *** Start programmer edit section *** (РазрешНаСтроит.НомерРазрешения Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.НомерРазрешения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.НомерРазрешения Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.НомерРазрешения Set start)
                this.fНомерРазрешения = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.НомерРазрешения Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.НомерРазрешения Set end)
            }
        }
        
        /// <summary>
        /// Разреш на строит.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.ОбъектСтроит CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.ОбъектСтроит CustomAttributes)
        public virtual IIS.RS_3.DetailArrayOfОбъектСтроит ОбъектСтроит
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Get start)
                if ((this.fОбъектСтроит == null))
                {
                    this.fОбъектСтроит = new IIS.RS_3.DetailArrayOfОбъектСтроит(this);
                }
                IIS.RS_3.DetailArrayOfОбъектСтроит result = this.fОбъектСтроит;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Set start)
                this.fОбъектСтроит = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ОбъектСтроит Set end)
            }
        }
        
        /// <summary>
        /// Разреш на строит.
        /// </summary>
        //  *** Start programmer edit section *** (РазрешНаСтроит.ЗастройщОрг CustomAttributes)

        //  *** End programmer edit section *** (РазрешНаСтроит.ЗастройщОрг CustomAttributes)
        public virtual IIS.RS_3.DetailArrayOfЗастройщОрг ЗастройщОрг
        {
            get
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Get start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Get start)
                if ((this.fЗастройщОрг == null))
                {
                    this.fЗастройщОрг = new IIS.RS_3.DetailArrayOfЗастройщОрг(this);
                }
                IIS.RS_3.DetailArrayOfЗастройщОрг result = this.fЗастройщОрг;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Get end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Set start)

                //  *** End programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Set start)
                this.fЗастройщОрг = value;
                //  *** Start programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Set end)

                //  *** End programmer edit section *** (РазрешНаСтроит.ЗастройщОрг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РазрешНаСтроитE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РазрешНаСтроитE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РазрешНаСтроитE", typeof(IIS.RS_3.РазрешНаСтроит));
                }
            }
            
            /// <summary>
            /// "РазрешНаСтроитL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РазрешНаСтроитL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РазрешНаСтроитL", typeof(IIS.RS_3.РазрешНаСтроит));
                }
            }
        }
    }
}
